### ISSUE TITLE
Cleanup formatting of known types

### ISSUE THREAD

**Issue by richardszalay** [ewerkman/plumber-sc#11]
It would be nice to have type names cleaned up for display. For example, if you take a look at GetShopBlock you see these inputs/outputs

```
Input: System.Collections.Generic.IEnumerable`1[[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]
Output: System.Collections.Generic.IEnumerable`1[[Sitecore.Commerce.Plugin.Shops.Shop, Sitecore.Commerce.Plugin.Shops, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null]]
```

This would look much nicer as:

```
Input: IEnumerable<string>
Output: IEnumerable<Sitecore.Commerce.Plugin.Shops.Shop, Sitecore.Commerce.Plugin.Shops>
```

You could always have a checkbox for disabling the prettifying, and you could even take it a step further and omit the assembly name entirely since the type's namespace usually makes it redundant

**Comment by ewerkman** [comment]
Totally agree :-) Happy to take a PR on this one. And I'll put it on the backlog.

**Comment by richardszalay** [comment]
Just a quick update: I've written a parser and formatter than I'm quite happy with. It won't deal with some edgecases around malformed types, but it should tackle complex generic types if they're properly CLR-formatted.

Here's the output from my most complicated stress test:

Input:

``System.Collections.Generic.IDictionary`2[[System.Int32], [System.Collections.Generic.IDictionary`2[[Sitecore.Commerce.Plugin.Shops.Shop, Sitecore.Commerce.Plugin.Shops, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null], [System.Tuple`2[[System.String], [Sitecore.Commerce.Plugin.Shops.Shop, Sitecore.Commerce.Plugin.Shops, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null]]], [System.Collections.Generic.IDictionary`2[[Sitecore.Commerce.Plugin.Shops.Shop, Sitecore.Commerce.Plugin.Shops, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null], [Sitecore.Commerce.Plugin.Shops.Shop, Sitecore.Commerce.Plugin.Shops, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null]]]]``

Output:

`IDictionary<int, IDictionary<Sitecore.Commerce.Plugin.Shops.Shop, Tuple<string, Sitecore.Commerce.Plugin.Shops.Shop>>>`

Here it is broken out to help understand the test case:

```
IDictionary<
  int,
  IDictionary<
    Sitecore.Commerce.Plugin.Shops.Shop, 
    Tuple<
      string, 
      Sitecore.Commerce.Plugin.Shops.Shop
    >
  >
>
```

Next steps are to integrate into the Vue app, which might require some reading on my behalf (I'm familiar with React/Redux, but not Vue).

Would you mind if I added Jest to the project so I can include my tests?

**Comment by ewerkman** [comment]
Hi Richard, no problem, go ahead.
Erwin

**Comment by ewerkman** [comment]
It's in release 1.0-beta-6

Thanks @richardszalay!
