### ISSUE TITLE
CI build does not run tests

### ISSUE THREAD

**Issue by richardszalay** [ewerkman/plumber-sc#18]
Your Vue template contains support for Jest via `npm test` (or `npm run unit` for just unit tests), but the CI build doesn't appear to run them.

See this build as an example: https://travis-ci.org/ewerkman/plumber-sc/builds/352767337

**Comment by ewerkman** [comment]
That's correct. Because I didn't create any tests (living dangerously ;-)) the Travis build failed, so I turned it off. 

You can turn it on buy changing "tests" in package.json back to "test"
